### ISSUE TITLE
Tingting's feedback

### ISSUE THREAD

**Issue by DragonSake** [jessedegroothva/web-app-from-scratch-2223#1]
Denk aan:
* Logo?
* Als je op een afbeelding drukt, is het niet duidelijk dat je terug kan gaan door op de afbeelding te drukken (maak een "X" ofzo)
* Beschrijving bij het plaatje en misschien een "lees meer" of een deel van de tekst laten zien om meer nieuwsgierigheid op te wekken (geef meer context voor de informatie)

**Comment by jessedegroothva** [comment]
done
